## 예외 처리

백기선님 온라인 라이브 스터디 과제 풀이입니다.

### 학습할 것 (필수)

- 자바에서 예외 처리 방법 (try catch, throw, throws, finally)
- 자바가 제공하는 예외 계층 구조
- Exception과 Error의 차이
- RuntimeException과 RE가 아닌 것의 차이
- 커스텀한 예외 만드는 방법

### 자바에서 예외 처리 방법 (try catch, throw, throws, finally)

프로그램의 실행도중에 발생하는 에러는 어쩔 수 없지만, 예외는 프로그래머가 이에 대한 처리를 미리 해주어야 한다. 예외처리란, <span style = "background-color:#FAF4C0">프로그램 실행 시 발생할 수 있는 예기치 못한 예외의 발생에 대비한 코드를 작성하는 것</span>이며, 예외처리의 목적은 예외의 발생으로 인한 실행 중인 프로그램의 갑작스런 비정상 종료를 막고, 정상적인 실행상태를 유지할 수 있도록 하는 것이다.

```
try {
    ... // 예외가 발생할 가능성이 있는 문장들
    catch (Exception e1) {
        Exception1이 발생했을 경우, 이를 처리하기 위한 문장
    } ...
}
```

키워드 `throw`를 사용해서 프로그래머가 고의로 예외를 발생시킬 수 있으며 방법은 아래의 순서를 따르면 된다.

- 먼저, 연산자 new를 이용해서 발생시키려는 예외 클래스의 객체를 만든 다음
    - Exception e = new Exception("고의발생");
- 키워드 throw를 이용해서 예외를 발생시킨다.
    - throw e;

```
try {
    Exception e = new Exception("고의");
    throw e;
} catch (Exception e) {
    ... // 에러 메시지
}
```

키워드 `throws`를 이용하여 메서드에 예외를 선언할 수 있다.

```
void method() throws Exception1, Exception2 ... {
    ... // 메서드의 내용
}
```

이렇게 예외를 선언하면, 이 예외뿐만 아니라 그 자손타입의 예외까지도 발생할 수 있다는 점에 주의한다. 앞서 오버라이딩에서 살펴본 것과 같이, 오버라이딩할 때는 단순히 선언된 예외의 개수가 아니라 상속관계까지 고려해야 한다.

`finally` 블럭은 예외의 발생여부에 상관없이 실행되어야할 코드를 포함시킬 목적으로 사용된다. try - catch문의 끝에 선택적으로 덧붙여 사용할 수 있으며 try - catch - finally의 순서로 구성된다.

```
try {
    ... 
} catch (Exception e1) {
    ...
} finally {
    ... // 예외의 발생여부에 관계없이 항상 수행되어야하는 문장들을 넣는다.
}
```

### 자바가 제공하는 예외 계층 구조

![](https://user-images.githubusercontent.com/78870076/125567300-1f03432e-ee04-460b-958b-128f2fc37296.png)

자바에서는 실행 시 발생할 수 있는 오류를 클래스로 정의하였다. 앞서 배운 것처럼 모든 클래스의 조상은 `Object` 클래스이므로 `Exception`과 `Error` 클래스 역시 Object 클래스의 자손들이다. 모든 예외의 최고 조상은 Exception 클래스이다.

### Exception과 Error의 차이

런타임 에러를 방지하기 위해서는 프로그램의 실행도중 발생할 수 있는 모든 경우의 수를 고려하여 이에 대한 대비를 하는 것이 필요하다. 자바에서는 <span style = "background-color:#FAF4C0">실행 시 발생할 수 있는 프로그램 오류</span>를 `Error`와 `Exception`으로 구분하였다.

- 에러 : 프로그램 코드에 의해서 수습될 수 없는 심각한 오류
- 예외 : 프로그램 코드에 의해서 수습될 수 있는 다소 미약한 오류

### RuntimeException과 RE가 아닌 것의 차이

`RuntimeException`의 클래스들은 주로 프로그래머의 실수에 의해서 발생될 수 있는 예외들로 자바의 프로그래밍 요소들과 관계가 깊다. 예를 들면, 배열의 범위를 벗어난다던가, 값이 null인 참조변수의 멤버를 호출하려 했다던가, 클래스간의 형변환을 잘못했다던가, 정수를 0으로 나누려고 하는 경우에 발생한다.

`Exception` 클래스들은 주로 외부의 영향으로 발생할 수 있는 것들로써, 프로그램의 사용자들의 동작에 의해서 발생하는 경우가 많다. 예를 들면, 존재하지 않는 파일의 이름을 입력했다던가, 실수로 클래스의 이름을 잘못 적었다던가, 또는 입력한 데이터 형식이 잘못된 경우에 발생한다.

### 커스텀한 예외 만드는 방법

기존의 정의된 예외 클래스 외에 필요에 따라 프로그래머가 새로운 예외 클래스를 정의하여 사용할 수 있다. 보통 `Exception` 클래스 또는 `RuntimeException` 클래스로부터 상속받아 클래스를 만들지만, 필요에 따라서 알맞은 예외 클래스를 선택할 수 있다.

```
class MyException extends Exception {
    MyException (String msg) {
        super(msg); // 조상인 Exception의 생성자를 호출
    }
}
```

Exception 클래스로부터 상속받아서 MyException 클래스를 만들었다. 필요하다면, 멤버 변수나 메서드를 추가할 수 있다.

```
class MyException extends Exception {
    private final int ERR_CODE;

    MyException(String msg, int errCode) { // 생성자
        super(msg);
        ERR_CODE = errCode;
    }

    MyException(String msg) { // 생성자
        this.ERRCODE = 100 // ERR_CODE를 100으로 초기화
    }

    publc int getErrCode() {
        return ERR_CODE; 
    }
}
```